account/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name="account/login.html"), name="login"),
	path('register/', views.register, name="register"),
	path('dashboard/', views.dashboard, name="dashboard"),
	path('profile/', views.profile, name="profile"),
	path('profile/edit', views.edit, name="edit"),
	path('logout/', views.logout_view, name="logout"),
	path('change-password/', views.change_password, name="change_password"),
	path('users/follow/', views.user_follow, name="user_follow"),
	path('users/', views.user_list, name="user_list"),
	path('user/<username>/', views.user_detail, name="user_detail"),
	path('', views.redirect_to_profile, name="redirect_to_profile"),
	# path('publications_list/', views.publication_list, name="publications_list"),
	# path('change-password/', auth_views.PasswordChangeView.as_view(template_name="account/edit_account.html", success_url=reverse_lazy('account:edit')), name="change_password"), # reverse_lazy('password_change_done')
	# path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name="account/profile.html"), name="change_password_done"),
]

instagram_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', views.redirect_to_login, name="redirect_to_login"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('publications/', include('publications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path
from . import views

app_name = 'publications'

urlpatterns = [
	path('create/', views.create_publication, name="create_publication"),
	path('like/', views.publication_like, name="like"),
	path('', views.publication_list, name="list"),
	path('comment_publication/', views.publication_comments_list, name="comment_publication"),
	path('delete_comment/', views.delete_comment, name="delete_comment"),
	# path('users_likes/', views.get_users_likes, name="get_users_likes"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

def user_directory_path(instance, filename):
	return 'users/{0}/avatar/{1}'.format(instance.user.username, filename)

class Contact(models.Model):
	user_from = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='rel_from_set', on_delete='CASCADE')
	user_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='rel_to_set', on_delete='CASCADE')
	created = models.DateTimeField(auto_now_add=True, db_index=True)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return '{} follows {}'.format(self.user_from, self.user_to)

class CustomUser(AbstractUser):
	first_name = models.CharField('first name', max_length=30, blank=False)
	last_name = models.CharField('last name', max_length=150, blank=False)
	email = models.EmailField('email address', blank=False)
	following = models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False)

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete='CASCADE')
	date_of_birth = models.DateField(blank=True, null=True)
	biography = models.TextField(blank=True, null=True)
	avatar = models.ImageField(upload_to=user_directory_path, blank=True) #'users/%Y/%m/%d'
	phone = models.CharField('phone', max_length=30, blank=True)

	def __str__(self):
		return 'Profile for user: {}'.format(self.user.username)


	

account/forms.py
from django import forms
from django.forms import ModelForm
from .models import CustomUser, Profile
from django.contrib.auth import get_user_model, password_validation

class RegistrationForm(ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	confirm_password = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

	class Meta:
		model = CustomUser
		fields = ['first_name', 'last_name', 'username', 'email']

	def clean_confirm_password(self):
		cd = self.cleaned_data

		if cd['password'] != cd['confirm_password']:
			raise forms.ValidationError('The fields password and confirm password don\'t match.')

		return cd['password']

class UserEditForm(ModelForm):
	class Meta:
		model = CustomUser
		fields = ('first_name', 'last_name', 'username', 'email')

class ProfileEditForm(ModelForm):
	class Meta:
		model = Profile
		fields = ('date_of_birth', 'avatar', 'biography', 'phone')

class SetPasswordForm(forms.Form):
	error_messages = {
    'password_mismatch': "The two password fields didn't match.",
	}

	new_password1 = forms.CharField(
    label="New password",
    widget=forms.PasswordInput,
    strip=False,
    help_text=password_validation.password_validators_help_text_html(),
	)
	new_password2 = forms.CharField(
    label="New password confirmation",
    strip=False,
    widget=forms.PasswordInput,
	)

	def __init__(self, user, *args, **kwargs):
		self.user = user
		super().__init__(*args, **kwargs)

	def clean_new_password2(self):
		password1 = self.cleaned_data.get('new_password1')
		password2 = self.cleaned_data.get('new_password2')

		if password1 and password2:
			if password1 != password2:
				raise forms.ValidationError(
					self.error_messages['password_mismatch'],
					code='password_mismatch',
				)
			password_validation.validate_password(password2, self.user)
		return password2

	def save(self, commit=True):
		password = self.cleaned_data["new_password1"]
		self.user.set_password(password)
		if commit:
			self.user.save()
		return self.user

class PasswordChangeForm(SetPasswordForm):
	error_messages = {
    **SetPasswordForm.error_messages,
    'password_incorrect': "Your old password was entered incorrectly. Please enter it again.",
	}
	old_password = forms.CharField(
    label="Old password",
    strip=False,
    widget=forms.PasswordInput(attrs={'autofocus': True}),
	)

	field_order = ['old_password', 'new_password1', 'new_password2']

	def clean_old_password(self):
		old_password = self.cleaned_data["old_password"]

		if not self.user.check_password(old_password):
		  raise forms.ValidationError(
		    self.error_messages['password_incorrect'],
		    code='password_incorrect',
		  )
		return old_password
	

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, UserEditForm, ProfileEditForm, PasswordChangeForm
from .models import CustomUser, Profile, Contact
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from publications.models import Publication, Comment
from publications.forms import CommentForm
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST
import json
from actions.utils import create_action
from actions.models import Action

def register(request):
	if request.method == 'POST':
		registration_form = RegistrationForm(request.POST)
		if registration_form.is_valid():
			new_user = registration_form.save(commit=False)
			new_user.set_password(registration_form.cleaned_data['password'])
			new_user.save()
			profile = Profile.objects.create(user=new_user)
			create_action(new_user, 'has created an account')

			return redirect('account:dashboard')
	else:
		registration_form = RegistrationForm()

	return render(request, 'account/register.html', {'registration_form': registration_form})

@login_required
def edit(request):
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user, data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)

		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			# messages.success(request, 'Profile updated!', extra_tags='is-primary')
			return redirect('account:edit')
		else:
			# messages.error(request, 'Invalid information!', extra_tags='is-danger')
			return redirect('account:edit')

	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)
		password_form = PasswordChangeForm(user=request.user)
	
	return render(request, 'account/edit_account.html', {'user_form': user_form, 'profile_form': profile_form, 'password_form': password_form})

@login_required
def change_password(request):
	if request.method == 'POST':
		password_form = PasswordChangeForm(user=request.user, data=request.POST)

		if password_form.is_valid():
			password_form.save()
			return redirect('account:edit')
	else:
		password_form = PasswordChangeForm(instance=request.user)
	
	user_form = UserEditForm(instance=request.user)
	profile_form = ProfileEditForm(instance=request.user.profile)

	return render(request, 'account/edit_account.html', {'user_form': user_form, 'profile_form': profile_form, 'password_form': password_form})

@login_required
def dashboard(request):
	# display all actions by default
	# actions = Action.objects.exclude(user=request.user)
	# following_ids = request.user.following.values_list('id', flat=True)
	# if following_ids:
	# 	# if user is following others, retrieve only their actions
	# 	actions = actions.filter(user_id__in=following_ids).select_related('user', 'user__profile').prefetch_related('target')
	# actions[:10]
	publications = Publication.objects.all()
	return render(request, 'account/dashboard.html', {'section': 'dashboard', 'publications': publications})


@login_required
def profile(request):
	return render(request, 'account/profile.html')

@login_required
def logout_view(request):
	logout(request)
	return redirect('account:login')

@login_required
def user_list(request):
	users = CustomUser.objects.filter(is_active=True)
	return render(request, 'account/user/list.html', {'section': 'explore', 'users': users})

@login_required
def user_detail(request, username):
	usr = get_object_or_404(CustomUser, username=username, is_active=True)
	return render(request, 'account/user/detail.html', {'section': 'explore', 'usr': usr})

@ajax_required
@require_POST
@login_required
def user_follow(request):
	data = json.loads(request.body.decode('utf-8'))
	user_id = data.get('id')
	action = data.get('action')
	if user_id and action:
		try:
			user = CustomUser.objects.get(id=user_id)
			if action == 'follow':
				Contact.objects.get_or_create(user_from=request.user, user_to=user)
				create_action(request.user, 'is following', user)
			else:
				Contact.objects.filter(user_from=request.user, user_to=user).delete()
			return JsonResponse({'status': 'ok'})
		except User.DoesNotExist:
			return JsonResponse({'status': 'ko'})
	return JsonResponse({'status': 'ko'})

@login_required
def redirect_to_profile(request):
	return redirect('account:profile')

# @login_required
# def publication_list(request):
# 	publications = Publication.objects.all()
# 	paginator = Paginator(publications, 6)
# 	page = request.GET.get('page')
# 	print(page)
# 	try:
# 		publications = paginator.page(page)
# 	except PageNotAnInteger:
# 		publications = paginator.page(1)
# 	except EmptyPage:
# 		if request.is_ajax():
# 			return HttpResponse('')
# 		publications = paginator.page(paginator.num_pages)
# 	if request.is_ajax():
# 		return render(request, 'includes/list_ajax.html', { 'publications': publications})
# 	return render(request, 'account/profile.html', {'publications': publications})

# @login_required
# def profile(request):
# 	publications = Publication.objects.all()
# 	paginator = Paginator(publications, 6)
# 	page = request.GET.get('page')
# 	try:
# 		publications = paginator.page(page)
# 	except PageNotAnInteger:
# 		publications = paginator.page(1)
# 	except EmptyPage:
# 		if request.is_ajax():
# 			return HttpResponse('')
# 		publications = paginator.page(paginator.num_pages)
# 	if request.is_ajax():
# 		return render(request, 'includes/list_ajax.html', { 'publications': publications})
# 	return render(request, 'account/profile.html', {'publications': publications})

account/templates/includes/comment_list.html
{% load thumbnail %}

<ul class="comment-list">
  {% with comments=pub.comments.all %}
    {% for comment in comments %}
      <li>
        <!-- {% thumbnail comment.user.profile.avatar "50x50" crop="top" as im %}
          <img src="{{ im.url }}" alt="" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        {{ comment.user.username }} - {{ comment.body }} -->
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <img src="{{ comment.user.profile.avatar.url }}">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>{{ comment.user.username }}</strong> <!-- <small>@johnsmith</small> <small>31m</small> -->
                <br>
                {{ comment.body }}
              </p>
            </div>
            <nav class="level is-mobile">
              <div class="level-left">
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-reply"></i></span>
                </a>
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                </a>
                <a class="level-item">
                  <span class="icon is-small"><i class="fas fa-heart"></i></span>
                </a>
              </div>
            </nav>
          </div>
          {% if pub.user == request.user %}
            <div class="media-right">
              <form action="{% url 'publications:delete_comment' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <button class="delete" type="submit"></button>
              </form>
            </div>
          {% endif %}
        </article>
      </li>
    {% empty %}
      <li>
        <p class="no-comments">No comments yet.</p>
      </li>
    {% endfor %}
  {% endwith %}
</ul>

account/templates/includes/footer.html
<footer>
	<div class="container is-fluid">
		<p class="has-text-grey-dark">
			&copy; Instagram clone app | rpj17 | Legal
		</p>
	</div>
</footer>

account/templates/includes/header.html
{% load account_tags %}
<header>
	<nav class="navbar" role="navigation" aria-label="main navigation">
		<div class="container is-fluid">
			<div class="navbar-brand">
				<a href="{% url 'account:dashboard' %}" class="navbar-item is-primary">
					Instagram Clone App
				</a>
			
				<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="mainNavbar">
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
				</a>
			</div>
			
			<div id="mainNavbar" class="navbar-menu">
				<div class="navbar-end">
					<a href="{% url 'account:user_list' %}" class="navbar-item">
						<span class="icon has-text-primary">
							<!-- <i class="fas fa-search"></i> --> <!-- lupa --> 
							<!-- <i class="fas fa-th-large"></i> -->
							<!-- <i class="fas fa-table"></i> -->
							<i class="fas fa-th"></i>
						</span>
						<span>
							Explore
						</span>
					</a>
					<!-- <a href="#" class="navbar-item">Notifications</a> -->
					<div class="navbar-item has-dropdown"> <!-- is-hoverable -->
						<a class="navbar-link is-arrowless">
							<span class="icon has-text-primary">
								<!-- <i class="fas fa-comments"></i> -->
								<!-- <i class="fas fa-comment-alt"></i> -->
								<i class="fas fa-bell"></i>
							</span>
							<span>
								Notifications
							</span>
						</a>
						<div class="navbar-dropdown">
							{% get_user_notifications as notifications %}
							{% if notifications %}
								{% for action in notifications %}
									<a href="#" class="navbar-item">
										<span class="icon has-text-primary">
											{% if action.verb == 'likes' %}
												<i class="fas fa-heart"></i>
											{% else %}
												<i class="fas fa-users"></i>
											{% endif %}
										</span>
										<span>
											{% if action.user %}
												{{ action.user }} 
											{% endif %}
											{% if action.verb %}
												{{ action.verb }}
											{% endif %}
											{% if action.target %}
												{{ action.target }}
											{% endif %}
										</span>
									</a>
								{% endfor %}
							{% else %}
								<a href="" class="navbar-item">
									No notifications yet.
								</a>
							{% endif %}
							<!-- <a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-users"></i>
								</span>
								<span>
									Notification 1
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-user"></i>
								</span>
								<span>
									Notification 2
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-user-alt"></i>
								</span>
								<span>
									Notification 3
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-user-friends"></i>
								</span>
								<span>
									Notification 4
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-user-plus"></i>
								</span>
								<span>
									Notification 5
								</span>
							</a>
							<hr class="navbar-divider">
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-comment-alt"></i>
								</span>
								<span>
									Notification 6
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-comments"></i>
								</span>
								<span>
									Notification 7
								</span>
							</a>
							<a href="#" class="navbar-item">
								<span class="icon has-text-primary">
									<i class="fas fa-comment"></i>
								</span>
								<span>
									Notification 8
								</span>
							</a> -->
						</div>
					</div>
					<a href="{% url 'account:profile' %}" class="navbar-item">
						<span class="icon has-text-primary">
							<i class="fas fa-user-circle"></i>
						</span>
						<span>Profile</span>
					</a>
					<!-- <div class="navbar-item">
										<div class="buttons">
											<a href="#" class="button is-primary">
												<strong>Sign up</strong>
											</a>
											<a href="#" class="button is-light">
												Log in
											</a>
										</div>
									</div> -->
				</div>
			</div>
		</div>
	</nav>
</header>

account/templates/includes/list_ajax.html
{% load account_tags %}

{% load thumbnail %}

{% for pub in publications %}
  <div class="publication">
    <a class="profile-button-image">
      {% thumbnail pub.image "450x450" crop="top" as im %}
        <img src="{{ im.url }}" alt="" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
    </a>
    <div class="modal">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="image">
          <img src="{{ pub.image.url }}" alt="" class="modal-image">
        </div>
        {% with total_likes=pub.users_like.count users_like=pub.users_like.all %}
        <ul>
          <li>
            <a href="" data-id="{{ pub.id }}" data-action="{% if user in users_like %}un{% endif %}like" class="like-button">
              <span class="icon is-small {% if user in users_like %}has-text-primary{% endif %}">
                <i class="fas fa-heart"></i>
              </span>
            </a>
            <span class="total-likes-number">
              {{ total_likes }}
            </span>
          </li>
          <li>
            <a href="" class="btn-comment-jump">
              <span class="icon is-small">
                <i class="fas fa-comment"></i>
              </span>
            </a>
          </li>
        </ul>
        <span class="is-size-7">
          {% with pub_id=pub.id %}
            {% if users_like %}
              Likes to
              {% for user in users_like %}
                {% if forloop.first %}
                  {{ user }}
                {% elif forloop.last %}
                  {% with pub_id=pub.id %}
                    and {% pubs_minus_one pub_id %} more.
                  {% endwith %}
                {% else %}

                {% endif %}
              {% endfor %}
            {% else %}
              No likes.
            {% endif %}
          {% endwith %}
        </span>
        {% endwith %}
        <hr>
        <p class="description">
          <strong>{{ user.username }}</strong> {{ pub.description }}
        </p>
        <form action="" method="post" class="comment-form">
          <div class="field">
            <textarea name="comment" id="id_comment" placeholder="Comment..." class="textarea" rows="2"></textarea>
          </div>
        </form>
      </div>
      <button class="modal-close is-large" aria-label="close"></button>
    </div>
  </div>
{% endfor %}

account/templates/includes/sidebar.html
sidebar